=== lealemseyoum/pmt-1.5.0/test/PmtInterpreterTest/AttrFacet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!-- 8-bit based number types -->
	<xsd:simpleType name="pmt_vint8">
		<xsd:list itemType="xsd:byte"/>
	</xsd:simpleType>
	<xsd:simpleType name="pmt_vuint8">
		<xsd:list itemType="xsd:unsignedByte"/>
	</xsd:simpleType>
	<!-- 16-bit based number types -->
	<xsd:simpleType name="pmt_vint16">
		<xsd:list itemType="xsd:short"/>
	</xsd:simpleType>
	<xsd:simpleType name="pmt_vuint16">
		<xsd:list itemType="xsd:unsignedShort"/>
	</xsd:simpleType>
	<!-- 32-bit based number types -->
	<xsd:simpleType name="pmt_vint32">
		<xsd:list itemType="xsd:int"/>
	</xsd:simpleType>
	<xsd:simpleType name="pmt_vuint32">
		<xsd:list itemType="xsd:unsignedInt"/>
	</xsd:simpleType>
	<!-- boolean types -->
	<xsd:simpleType name="pmt_vboolean">
		<xsd:list itemType="xsd:boolean"/>
	</xsd:simpleType>
	<!-- floating point types -->
	<xsd:simpleType name="pmt_vfloat">
		<xsd:list itemType="xsd:float"/>
	</xsd:simpleType>
	<xsd:simpleType name="pmt_vdouble">
		<xsd:list itemType="xsd:double"/>
	</xsd:simpleType>
	<!-- string types -->
	<xsd:simpleType name="pmt_vstring">
		<xsd:list itemType="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="uint32_10">
		<xsd:restriction base="xsd:unsignedInt">
			<xsd:minInclusive value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="uint32_20-100">
		<xsd:restriction base="uint32_10">
			<xsd:minInclusive value="20"/>
			<xsd:maxInclusive value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="color_rgbc">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Red"/>
			<xsd:enumeration value="Green"/>
			<xsd:enumeration value="Blue"/>
			<xsd:enumeration value="Cyan"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="color_rgbc_derived">
		<xsd:restriction base="color_rgbc"/>
	</xsd:simpleType>
	<xsd:simpleType name="color_rgb">
		<xsd:annotation>
			<xsd:documentation xml:lang="en">color_rgb definition</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="color_rgbc">
			<xsd:enumeration value="Red"/>
			<xsd:enumeration value="Green"/>
			<xsd:enumeration value="Blue"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:attribute name="Ref_Attr" type="color_rgbc_derived" default="Cyan"/>
	<xsd:attribute name="FixedAtrribute" type="color_rgbc" fixed="Green"/>
	<xsd:attribute name="UseAttribute1" type="xsd:string" use="required" fixed="1"/>
	<xsd:attribute name="UseAttribute2" type="color_rgbc" use="optional"/>
	<xsd:attribute name="UseAttribute3" type="color_rgbc" use="prohibited"/>
	<xsd:attribute name="EffectiveDate" type="xsd:string" default="2000-01-10"/>
	<xsd:complexType name="ComplexType3">
		<xsd:sequence>
			<xsd:element name="ABC" type="xsd:string"/>
			<xsd:element name="DEF" type="pmt_vint32"/>
		</xsd:sequence>
		<xsd:attribute name="Attr6" type="xsd:unsignedShort"/>
	</xsd:complexType>
	<xsd:complexType name="ComplexType2">
		<xsd:sequence>
			<xsd:element name="ABC" type="xsd:string"/>
			<xsd:element name="DEF" type="pmt_vint32"/>
		</xsd:sequence>
		<xsd:attribute ref="EffectiveDate" default="2000-01-10"/>
		<xsd:attribute name="Attr5" type="xsd:unsignedShort"/>
	</xsd:complexType>
	<xsd:element name="Ref_Element">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Ref_XYZ1" type="xsd:int"/>
				<xsd:element name="Ref_XYZ2" type="xsd:string"/>
				<xsd:element name="Ref_XYZ3" type="ComplexType3"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="ComplexType1">
		<xsd:sequence>
			<xsd:element name="XYZ3" type="xsd:string"/>
			<xsd:element name="XYZ4" type="pmt_vint32"/>
		</xsd:sequence>
		<xsd:attribute name="Attr4" type="uint32_20-100"/>
		<xsd:attribute name="Attr5" type="xsd:unsignedShort"/>
	</xsd:complexType>
	<xsd:attribute name="Timestamp" type="xsd:string" use="required">
		<xsd:annotation>
			<xsd:documentation>
			See section F.3.2 Timestamp Attribute
			</xsd:documentation>
		</xsd:annotation>
	</xsd:attribute>
	<xsd:element name="PmtRootElement">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="ABC5" type="uint32_20-100" nillable="true"/>
				<xsd:element name="ABC1" type="uint32_20-100"/>
				<xsd:element name="ABC2">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="XYZ1" type="color_rgb"/>
							<xsd:element name="XYZ2" type="pmt_vfloat"/>
						</xsd:sequence>
						<xsd:attribute name="Attr1" type="uint32_10"/>
						<xsd:attribute ref="Ref_Attr"/>
						<xsd:attribute name="Attr3" type="xsd:string"/>
						<xsd:attribute ref="Timestamp"/>
						<xsd:attribute ref="UseAttribute1"/>
						<xsd:attribute ref="UseAttribute2"/>
						<xsd:attribute ref="UseAttribute3"/>
						<xsd:attribute ref="FixedAtrribute"/>
						<xsd:attribute ref="EffectiveDate"/>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="ABC3">
					<xsd:simpleType>
						<xsd:restriction base="xsd:short">
							<xsd:enumeration value="2"/>
							<xsd:enumeration value="4"/>
							<xsd:enumeration value="6"/>
							<xsd:enumeration value="8"/>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element ref="Ref_Element"/>
				<xsd:element name="ABC4" type="ComplexType1"/>
				<xsd:element name="ABCD" type="ComplexType2"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== lealemseyoum/pmt-1.5.0/test/PmtInterpreterTest/AttFacet.xml
<?xml version="1.0" encoding="UTF-8"?>
<PmtRootElement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AttrFacet.xsd" xsi:SchemaLocation="AttrFacet.xsd">
	<ABC5 xsi:nil="true"/>
	<ABC1>21</ABC1>
	<ABC2 Timestamp="07/01/2002" Attr1="11" Attr3="1" FixedAtrribute="Green" Ref_Attr="Cyan" UseAttribute1="1" UseAttribute2="Red">
		<XYZ1>Blue</XYZ1>
		<XYZ2>11</XYZ2>
	</ABC2>
	<ABC3>2</ABC3>
	<Ref_Element attr9="99">
		<Ref_XYZ1>123</Ref_XYZ1>
		<Ref_XYZ2>test</Ref_XYZ2>
		<Ref_XYZ3 Attr6="2">
			<ABC attr7="333">1233</ABC>
			<DEF>32</DEF>
		</Ref_XYZ3>
	</Ref_Element>
	<ABC4>
		<XYZ3/>
		<XYZ4/>
	</ABC4>
	<ABCD Attr5="0" EffectiveDate="2000-01-10">
		<ABC/>
		<DEF/>
	</ABCD>
</PmtRootElement>
